# Generated by Django 4.2.8 on 2023-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subscribers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='Email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
