# Generated by Django 4.2.8 on 2023-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscribers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='Email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
