# Generated by Django 4.2.4 on 2023-11-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail', '0009_alter_hot_thrills_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality1', models.CharField(blank=True, help_text='Quality Ex: 720p', max_length=50, null=True)),
                ('size', models.CharField(blank=True, help_text='Size of file Ex: 2GB', max_length=50, null=True)),
                ('server1_1', models.CharField(blank=True, help_text='Download url', max_length=50, null=True)),
                ('server2_1', models.CharField(blank=True, help_text='Download url', max_length=50, null=True)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='detail.movie')),
            ],
            options={
                'verbose_name': 'Downloads',
                'verbose_name_plural': 'Downloadss',
            },
        ),
    ]
