# Generated by Django 4.2.4 on 2023-11-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloads',
            options={'verbose_name': 'Downloads', 'verbose_name_plural': 'Downloads'},
        ),
        migrations.AddField(
            model_name='downloads',
            name='Quality2',
            field=models.CharField(blank=True, help_text='Quality Ex: 720p', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='Quality3',
            field=models.CharField(blank=True, help_text='Quality Ex: 1080p', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='Quality4',
            field=models.CharField(blank=True, help_text='Quality Ex: 2160p', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server1_2',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server1_3',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server1_4',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server2_2',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server2_3',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='server2_4',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='Quality1',
            field=models.CharField(blank=True, help_text='Quality Ex: 420p', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='server1_1',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='server2_1',
            field=models.URLField(blank=True, help_text='Download url', max_length=500, null=True),
        ),
    ]
