# Generated by Django 4.2.4 on 2023-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_alter_downloads_options_downloads_quality2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloads',
            old_name='size',
            new_name='size1',
        ),
        migrations.AddField(
            model_name='downloads',
            name='size2',
            field=models.CharField(blank=True, help_text='Size of file Ex: 2GB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='size3',
            field=models.CharField(blank=True, help_text='Size of file Ex: 2GB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='size4',
            field=models.CharField(blank=True, help_text='Size of file Ex: 2GB', max_length=50, null=True),
        ),
    ]
