# Generated by Django 4.2.4 on 2023-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browse_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse_url', models.URLField(blank=True, help_text='If not poster image ', null=True)),
                ('browse_name', models.CharField(help_text='Enter the movie name', max_length=50)),
                ('browse_release_date', models.DateField()),
                ('browse_image', models.ImageField(help_text='If not image url', upload_to='movie_media')),
                ('browse_trailler', models.CharField(help_text='Enter the trailler id', max_length=900)),
            ],
        ),
    ]
