# Generated by Django 4.2.4 on 2023-11-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_browse_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='browse_update',
            options={'verbose_name': 'Browse slideshow', 'verbose_name_plural': 'Browse slideshow'},
        ),
        migrations.AddField(
            model_name='browse_update',
            name='browse_clip',
            field=models.URLField(blank=True, help_text='If have clip url (optional)', max_length=1000, null=True),
        ),
    ]
