# Generated by Django 4.2.4 on 2023-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_alter_browse_update_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browse_update',
            name='coming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='browse_update',
            name='browse_image',
            field=models.ImageField(blank=True, help_text='If not image url', null=True, upload_to='movie_media'),
        ),
        migrations.AlterField(
            model_name='browse_update',
            name='browse_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
