# Generated by Django 4.2.4 on 2023-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_browse_update_coming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browse_update',
            name='browse_clip',
            field=models.FileField(blank=True, help_text='If have clip', null=True, upload_to='movie_media'),
        ),
    ]
