# Generated by Django 4.2.4 on 2023-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_alter_browse_update_browse_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browse_update',
            name='browse_url',
            field=models.URLField(blank=True, help_text='If not poster image', null=True),
        ),
    ]
