# Generated by Django 4.2.4 on 2023-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_hot_thrills_text_hot_thrills_text_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_thrills',
            name='text',
            field=models.CharField(blank=True, help_text='If not text_image ( Optional )', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hot_thrills',
            name='text_upload_image',
            field=models.ImageField(blank=True, help_text='If not have text_image url ( Optional )', null=True, upload_to='movie_media'),
        ),
    ]
