# Generated by Django 4.2.4 on 2023-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0006_remove_movie_distibuted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hot_thrills',
            name='clip_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
